USE exampledb;

INSERT INTO toy (toyName, toyDescription, price, unitStock, image, rating, ageAbove, Q1, Q2, Q3, Q4, Q5)
VALUES ("Santa Claus GO Fish", "Ho ho ho! Santa Claus Go Fish (R) Card Game contains everything you need to play GO FISH, Christmas Matches, Slap Jack, and Old Maid— using 1 single convenient deck of kids cards. The game's playing cards are easy to read and illustrated with a fun selection of iconic Christmas images kids will love. The games are easy to learn and fun to play. This Christmas card game is sure to be a hit with the whole family! Fun Christmas games for kids game for ages 4 and up. The game's smaller size is perfect for use as a stocking stuffer. Christmas 2018 fun!", 7.99, 20, "https://images-na.ssl-images-amazon.com/images/I/61NlCd0DAmL._SL1033_.jpg", 3, 5, 1, 2, 5, 1, 1);

INSERT INTO toy (toyName, toyDescription, price, unitStock, image, rating, ageAbove, Q1, Q2, Q3, Q4, Q5)
VALUES ("Nerf Zombie Strike Brainsaw Blaster", "Defend the world from the zombie hordes with Nerf Zombie Strike blasters! Slice a path to shelter with the Brainsaw blaster. This dart-firing blaster also has a spinning foam saw blade for 2 ways to keep zombies away. Load the darts into the blaster to be ready for an attack whenever you venture into zombie-infested territory. Fire up the spinning foam blade and start cutting this zombie invasion down to size! Prime the blaster and pull the trigger to fire 1 dart at a time, and pull the string to make the blade spin. The Nerf Zombie Strike Brainsaw blaster comes with 8 Zombie Strike darts. Nerf and all related properties are trademarks of Hasbro.", 25.99, 25, "https://images-na.ssl-images-amazon.com/images/I/71pWO33IPXL._SL1500_.jpg", 5, 4, 5, 4, 1, 4, 1);

INSERT INTO toy (toyName, toyDescription, price, unitStock, image, rating, ageAbove, Q1, Q2, Q3, Q4, Q5)
VALUES ("Santa Claus GO Fish", "Ho ho ho! Santa Claus Go Fish (R) Card Game contains everything you need to play GO FISH, Christmas Matches, Slap Jack, and Old Maid— using 1 single convenient deck of kids cards. The game's playing cards are easy to read and illustrated with a fun selection of iconic Christmas images kids will love. The games are easy to learn and fun to play. This Christmas card game is sure to be a hit with the whole family! Fun Christmas games for kids game for ages 4 and up. The game's smaller size is perfect for use as a stocking stuffer. Christmas 2018 fun!", 7.99, 20, "https://images-na.ssl-images-amazon.com/images/I/61NlCd0DAmL._SL1033_.jpg", 3, 5, 1, 2, 5, 1, 1);

INSERT INTO toy (toyName, toyDescription, price, unitStock, image, rating, ageAbove, Q1, Q2, Q3, Q4, Q5)
VALUES ("Nerf Zombie Strike Brainsaw Blaster", "Defend the world from the zombie hordes with Nerf Zombie Strike blasters! Slice a path to shelter with the Brainsaw blaster. This dart-firing blaster also has a spinning foam saw blade for 2 ways to keep zombies away. Load the darts into the blaster to be ready for an attack whenever you venture into zombie-infested territory. Fire up the spinning foam blade and start cutting this zombie invasion down to size! Prime the blaster and pull the trigger to fire 1 dart at a time, and pull the string to make the blade spin. The Nerf Zombie Strike Brainsaw blaster comes with 8 Zombie Strike darts. Nerf and all related properties are trademarks of Hasbro.", 25.99, 25, "https://images-na.ssl-images-amazon.com/images/I/71pWO33IPXL._SL1500_.jpg", 5, 4, 5, 4, 1, 4, 1);

INSERT INTO toy (toyName, toyDescription, price, unitStock, image, rating, ageAbove, Q1, Q2, Q3, Q4, Q5)
VALUES ("Santa Claus GO Fish", "Ho ho ho! Santa Claus Go Fish (R) Card Game contains everything you need to play GO FISH, Christmas Matches, Slap Jack, and Old Maid— using 1 single convenient deck of kids cards. The game's playing cards are easy to read and illustrated with a fun selection of iconic Christmas images kids will love. The games are easy to learn and fun to play. This Christmas card game is sure to be a hit with the whole family! Fun Christmas games for kids game for ages 4 and up. The game's smaller size is perfect for use as a stocking stuffer. Christmas 2018 fun!", 7.99, 20, "https://images-na.ssl-images-amazon.com/images/I/61NlCd0DAmL._SL1033_.jpg", 3, 5, 1, 2, 5, 1, 1);